title: "My Portfolio"
description: "A portfolio website showcasing my work and projects."
url: "https://yourusername.github.io"
baseurl: ""

theme: jekyll-theme-minimal

nav:
  - title: "About Me"
    url: /about/
  - title: "Professional Experience"
    url: /professional_experience/
  - title: "Achievements"
    url: /achievements/
  - title: "Projects"
    url: /projects/
  - title: "Blog Posts"
    url: /blog/